/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example



fun main() {
    
}

fun replace(s: String): String {
    val vowels = setOf('a', 'e', 'i', 'o', 'u', 'A', 'E', 'I', 'O', 'U')
    val replacement = '!'
    val result = StringBuilder(s)
    for ((index, char) in s.withIndex()) {
        if (char in vowels) {
            result.setCharAt(index, replacement)
        }
    }
    return result.toString()
}