/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import kotlin.test.Test
import kotlin.test.assertEquals

class AppTest {
    @Test
    fun testReplace() {
        assertEquals("H!!", replace("Hi!"), "Failed for 'Hi!'")
        assertEquals("!H!! H!!", replace("!Hi! Hi!"), "Failed for '!Hi! Hi!'")
        assertEquals("!!!!!", replace("aeiou"), "Failed for 'aeiou'")
        assertEquals("!BCD!", replace("ABCDE"), "Failed for 'ABCDE'")
    }
}